-- Seed intervention_library. Idempotent via ON CONFLICT (slug).
-- Generated from supabase/seeds/intervention_library.json.

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'dispatcher_app_tier1_cloud',
  'Deploy cloud dispatcher + driver app (tier 1, full vendor)',
  NULL,
  'dispatch',
  'Order-to-dispatch time > 15 min; dispatcher juggles WhatsApp + Excel + phone; no real-time truck state; no audit trail for disputes.',
  '{"dispatch_tool_current":["whatsapp","excel","paper","none"],"trucks_min":20,"plants_min":1,"order_to_dispatch_min_gt":12}'::jsonb,
  60000,
  160000,
  'Year-1 all-in for 2 plants / 87 trucks: licence + onboarding + Arabic config + hardware (ruggedised tablets in trucks if not using driver phones) + 3 months of parallel-run support. Ongoing SaaS typ. $8-18/truck/month + $500-1500/plant/month. [recall: Command Alkon TrackIt, Sysdyne iStrada, Marcotte DISPATCH price bands]',
  'order_to_dispatch_min',
  -30,
  -60,
  'TAT -8 to -15 min via better queueing + ETA visibility; mixer utilisation +5 to +10 pp; dispute write-offs -30 to -50%.',
  10,
  'medium',
  ARRAY['gps_on_all_trucks', 'batch_plant_integration_feasible']::text[],
  false,
  'Driver UX must be Arabic-first with RTL. Many GCC drivers are South Asian (Urdu/Hindi/Bangla speakers) — multi-lingual driver app is a real requirement, not nice-to-have. Tablets in trucks get fried by Riyadh summer heat; spec IP65, operating temp to 60 C, or use driver BYOD with allowance.',
  '["Command Alkon TrackIt case studies [recall]","Sysdyne iStrada marketing [recall]","VERIFI + fleet telematics bundles [recall]"]'::jsonb,
  ARRAY['dispatch', 'digital_core', 'foundation']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'dispatcher_app_tier0_lightweight',
  'Lightweight dispatcher board (Airtable / Google Sheets + Twilio) before full vendor rollout',
  NULL,
  'dispatch',
  'Need dispatch visibility now but cannot wait 3-6 months for tier-1 rollout. Quick interim structure replaces WhatsApp scatter.',
  '{"dispatch_tool_current":["whatsapp","paper"],"trucks_min":10,"plants_min":1}'::jsonb,
  1500,
  6000,
  'Airtable Team or Google Workspace + Twilio SMS + 2-3 weeks of config by consultant. Ongoing $100-400/month.',
  'order_to_dispatch_min',
  -15,
  -35,
  'Forces process discipline that makes tier-1 rollout 30-50% faster when it comes.',
  2,
  'low',
  ARRAY[]::text[],
  true,
  'Arabic column headers and an Arabic-labelled status board for the dispatch room. Integrates with existing WhatsApp via Twilio WhatsApp Business API.',
  '["General SaaS deployment economics for a 90-truck fleet"]'::jsonb,
  ARRAY['dispatch', 'quick_win', 'bridge_solution']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'dispatch_playbook_roles',
  'Dispatcher role redesign + shift playbook',
  NULL,
  'dispatch',
  'Single dispatcher as single point of failure; no written rules for load allocation; ad-hoc decisions cause partial loads and plant-to-plant imbalance.',
  '{"plants_min":1,"trucks_min":15,"dispatcher_headcount_max":3}'::jsonb,
  2000,
  8000,
  'Consultant time to facilitate + print materials + optional 2-day training. No software cost.',
  'dispatch_consistency_index',
  15,
  40,
  'Removes key-person risk; reduces partial-load rate 1-3 pp when allocation rules are enforced.',
  2,
  'low',
  ARRAY[]::text[],
  true,
  'Patriarch-owner cultures often conflate dispatcher loyalty with capability. Document the rules in Arabic and get owner sign-off before rollout, or the new playbook will be overridden informally.',
  '["Consulting playbook norms for logistics SMEs"]'::jsonb,
  ARRAY['dispatch', 'process', 'quick_win', 'change_mgmt']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'multi_plant_load_balancer',
  'Cross-plant load balancing rules (nearest-plant + capacity-aware)',
  NULL,
  'dispatch',
  'Shared fleet but siloed plant dispatching leads to trucks crossing the city between plants; one plant queues while the other idles.',
  '{"plants_min":2,"trucks_shared_across_plants":true}'::jsonb,
  4000,
  25000,
  'Low end: config rules inside existing dispatch tool + facilitation. High end: build a simple optimiser on top of tier-1 dispatch vendor data.',
  'cross_plant_empty_km',
  -20,
  -50,
  'TAT -5 to -10 min on average; fuel -3 to -7%; trips per truck per day +0.3 to +0.8.',
  3,
  'medium',
  ARRAY['gps_visibility_both_plants']::text[],
  false,
  'Riyadh truck restriction zones make nearest-plant routing non-trivial: the cheaper plant by distance may be blocked during the restricted window. Rules must be time-of-day aware.',
  '["Industry practice [recall]: multi-plant operators routinely cite 10-25% empty-km reduction"]'::jsonb,
  ARRAY['dispatch', 'multi_plant', 'high_leverage']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'order_intake_standardisation',
  'Standardised order intake form + confirmation SLA',
  NULL,
  'dispatch',
  'Incomplete orders (missing site contact, access constraints, pump details) cause rework at dispatch time and partial loads sent to avoid cancellation.',
  '{"order_intake_channel_any_of":["phone","whatsapp","walk_in"]}'::jsonb,
  500,
  3000,
  'Form design + training + laminated Arabic checklist at order desk.',
  'order_rework_rate',
  -25,
  -60,
  'Partial-load rate -0.5 to -1.5 m3 per truck; dispute rate -10 to -20%.',
  1,
  'low',
  ARRAY[]::text[],
  true,
  'Include columns for: site access truck-size limit, pump type (line/boom), slump at point-of-pour, pour window, Iqama of site contact.',
  '["Lean ops norms for B2B logistics"]'::jsonb,
  ARRAY['dispatch', 'quick_win', 'quality']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'customer_slot_booking',
  'Site slot-booking portal with demurrage clause',
  NULL,
  'site_ops',
  'Trucks arrive at site and wait 30-90 min because no slot discipline; partial loads forced by customer under-readiness; reputational TAT blown.',
  '{"avg_site_wait_min_gt":20,"b2b_share_of_volume_gt":0.5}'::jsonb,
  8000,
  30000,
  'Simple web portal + SMS confirmations; or a module of the dispatch tier-1 tool. Demurrage clause requires legal review of contract.',
  'on_site_wait_min',
  -25,
  -55,
  'TAT -10 to -25 min; reject rate -0.2 to -0.5 pp (less re-temper / hot loads waiting in sun).',
  5,
  'medium',
  ARRAY['customer_willingness_to_sign_clause']::text[],
  false,
  'Demurrage is culturally sensitive with long-standing GCC contractor relationships. Patriarch-owner may resist. Alternative: soft priority-slot incentive rather than punitive charge.',
  '["Saudi Readymix IPO prospectus 2010 [recall]","GCP/VERIFI customer reports [recall]"]'::jsonb,
  ARRAY['site_ops', 'customer_discipline', 'TAT']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'pre_pour_site_readiness_call',
  'Pre-pour 30-minute site readiness confirmation call',
  NULL,
  'site_ops',
  'Trucks dispatched before pump is set / formwork signed off / site access confirmed; they then sit on site consuming TAT and rotation time.',
  '{"avg_site_wait_min_gt":15}'::jsonb,
  0,
  4000,
  'Process-only change; possibly 1 extra part-time tele-clerk at each plant ($400-700/month in KSA).',
  'on_site_wait_min',
  -10,
  -30,
  'Re-route rate (truck diverted after dispatch) -30 to -60%.',
  1,
  'low',
  ARRAY[]::text[],
  true,
  'Saudization-friendly role — can be filled by Saudi women (tele-work-compatible per MHRSD Saudization rules).',
  '["Widespread industry practice [recall]"]'::jsonb,
  ARRAY['site_ops', 'quick_win', 'TAT']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'weighbridge_kiosk_self_check',
  'Self-check driver kiosk at weighbridge (ANPR + Iqama scan)',
  NULL,
  'weighbridge',
  'Manual weigh ticketing causes 3-8 min per truck at the gate; bottleneck in peak dispatch; sometimes cause of partial records.',
  '{"weighbridge_process":["manual","semi_manual"],"trips_per_day_min":80}'::jsonb,
  15000,
  45000,
  'Per weighbridge: ANPR camera + kiosk + software + integration to batch + ticket printer. Two weighbridges = ~2x.',
  'weighbridge_cycle_min',
  -40,
  -70,
  'TAT -3 to -6 min; gate headcount -1 per shift per plant.',
  6,
  'medium',
  ARRAY['batch_system_api_available']::text[],
  false,
  'Arabic UI mandatory. Iqama (foreign worker ID) barcode standard in KSA; use as driver auth. Summer heat shelter needed for kiosk.',
  '["Libra Systems, Command Alkon weighbridge kiosk case studies [recall]"]'::jsonb,
  ARRAY['weighbridge', 'automation']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'rfid_gate_access',
  'RFID/UHF tagging of own fleet + ANPR for visitors',
  NULL,
  'weighbridge',
  'Gate dwell for known trucks is wasted time; visitor trucks (hire fleet) lack an audit trail.',
  '{"trucks_min":30,"hire_fleet_used":true}'::jsonb,
  12000,
  35000,
  'RFID tags $5-15 each x 100 trucks + 2 readers per plant + ANPR cam $2-4k.',
  'gate_dwell_sec',
  -50,
  -80,
  'Rotation capacity +2 to +4% at peak; dispute resolution near-instant.',
  4,
  'low',
  ARRAY[]::text[],
  false,
  'Ensure tag spec tolerates 60 C direct sun. Mount on windscreen upper-left to avoid re-read at wash bay.',
  '["Generic fleet RFID deployment benchmarks"]'::jsonb,
  ARRAY['weighbridge', 'automation', 'fleet']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'queue_management_screen',
  'Dynamic queue-management screen at batching deck',
  NULL,
  'weighbridge',
  'Drivers don''t know their position in queue; bunching at loading bays; dispatcher radio chaos.',
  '{"trucks_peak_concurrent_gt":8}'::jsonb,
  3000,
  10000,
  'Large outdoor LED screen + PC + integration feed from dispatch.',
  'loading_cycle_min',
  -5,
  -15,
  'Driver complaint rate visibly drops; dispatcher radio chatter -30 to -50%.',
  2,
  'low',
  ARRAY[]::text[],
  true,
  'Arabic + Urdu + English on rotating display; truck number in large digits readable from 30 m.',
  '["Common batching-plant retrofit [recall]"]'::jsonb,
  ARRAY['weighbridge', 'quick_win', 'driver_ux']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'batch_cycle_time_audit',
  'Batching cycle-time audit + recipe standardisation',
  NULL,
  'batching',
  'Mixer cycle drifting from spec (e.g. 4:30 actual vs. 3:30 design) eats capacity; ad-hoc recipe variants inflate changeover.',
  '{"mixer_utilisation_pct_lt":70,"recipe_count_gt":25}'::jsonb,
  4000,
  15000,
  '2-3 week engineer time + data extraction from batch controller.',
  'batch_cycle_sec',
  -10,
  -25,
  'Throughput +5 to +12 m3/hr per mixer; recipe changeovers -30 to -50%.',
  3,
  'medium',
  ARRAY['batch_controller_data_exportable']::text[],
  false,
  'Riyadh summer: admixture dosing tuned for 40+ C paste temp may need adjustment per shift.',
  '["Sysdyne, Marcotte audit methodologies [recall]"]'::jsonb,
  ARRAY['batching', 'throughput']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'recipe_rationalisation',
  'Recipe portfolio rationalisation (SKU reduction)',
  NULL,
  'batching',
  'Too many near-duplicate recipes (e.g. 12 variants of C32/40 with trivial admixture tweaks) cause waste, batching errors, and slow changeovers.',
  '{"recipe_count_gt":40}'::jsonb,
  3000,
  10000,
  'Tech manager + QC engineer time; consultant facilitation optional.',
  'active_recipe_count',
  -30,
  -60,
  'Batching error -20 to -40%; silo utilisation +5 to +10%.',
  3,
  'low',
  ARRAY[]::text[],
  true,
  'Megaproject specs (NEOM, Red Sea, Diriyah) each impose bespoke recipes; rationalise non-project portfolio first.',
  '["Lean ops SKU rationalisation norms"]'::jsonb,
  ARRAY['batching', 'quality', 'quick_win']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'moisture_probe_automation',
  'Aggregate moisture probes feeding batch controller',
  NULL,
  'batching',
  'Manual moisture adjustment is error-prone; causes slump variability and rejects; overdoses water or admixture.',
  '{"moisture_adjustment_process":["manual","none"],"reject_rate_pct_gt":1}'::jsonb,
  8000,
  25000,
  'Per plant: 2-4 Hydronix/similar probes + integration.',
  'slump_variance_cm',
  -30,
  -60,
  'Reject rate -0.3 to -1.0 pp; admixture spend -5 to -12%.',
  4,
  'medium',
  ARRAY['pic_or_plc_accepts_probe_input']::text[],
  false,
  'Riyadh aggregate sources often dry; probes pay back faster in mixed-aggregate plants.',
  '["Hydronix customer case studies [recall]"]'::jsonb,
  ARRAY['batching', 'quality', 'automation']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'silo_inventory_sensors',
  'Cement + aggregate silo level sensors with auto-reorder',
  NULL,
  'batching',
  'Stockouts stop production mid-shift; emergency cement deliveries at premium price; fines for late customer orders.',
  '{"silo_monitoring":["manual","visual","none"]}'::jsonb,
  8000,
  25000,
  'Per plant: radar/ultrasonic sensors on 4-8 silos + telemetry + dashboard.',
  'stockout_hours_per_month',
  -50,
  -90,
  'Emergency delivery premium -60 to -90%; safety stock can be reduced 10-25%.',
  4,
  'low',
  ARRAY[]::text[],
  false,
  'Cement cartel discipline in KSA means alternate suppliers limited on short notice; stockout cost is high.',
  '["Endress+Hauser, Siemens, Bindicator level-sensor case studies [recall]"]'::jsonb,
  ARRAY['batching', 'inventory']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'telematics_gps_basic',
  'Fleet telematics / GPS (tier 1, location + ignition + speed)',
  NULL,
  'fleet',
  'No ground truth on truck location; TAT reported by driver, gamed; fuel theft; unsafe driving.',
  '{"gps_coverage_pct_lt":80,"trucks_min":15}'::jsonb,
  12000,
  30000,
  'Hardware $150-350/truck installed + $8-15/truck/month SaaS. 87 trucks = ~$15-30k year-1.',
  'fuel_consumption_l_per_100km',
  -5,
  -12,
  'TAT accuracy unlocks every dispatch intervention; unsafe-event rate -20 to -40%.',
  6,
  'low',
  ARRAY[]::text[],
  false,
  'MOT Saudi Arabia ''Wasl'' integration is mandatory for commercial fleets >3.5t — vendor must be Wasl-certified.',
  '["Geotab / Mix Telematics customer reports [recall]"]'::jsonb,
  ARRAY['fleet', 'foundation', 'regulatory']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'telematics_concrete_sensors',
  'In-drum concrete sensors (slump, temperature, water-add)',
  NULL,
  'fleet',
  'No in-transit QC visibility; slump adjusted by driver eyeballing; rejects caught only at site when truck is already idle.',
  '{"reject_rate_pct_gt":1.5,"avg_delivery_radius_km_gt":15,"trucks_min":20}'::jsonb,
  150000,
  400000,
  'VERIFI / Sensocrete / Command Alkon MIX-R style: $2-4k hardware/truck + $30-80/truck/month. 87 trucks fully fitted = $175-350k year-1.',
  'reject_rate_pct',
  -30,
  -70,
  'Water addition at site -30 to -60%; fuel -2 to -5%; customer dispute win rate near 100%.',
  12,
  'high',
  ARRAY['telematics_gps_basic', 'driver_training_plan']::text[],
  false,
  'Riyadh 40+ C summer drives major paste temperature issues; in-drum temp monitoring has outsized value here.',
  '["VERIFI public case studies [recall]","Command Alkon MIX-R marketing [recall]"]'::jsonb,
  ARRAY['fleet', 'quality', 'high_cost']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'preventive_maintenance_program',
  'Structured preventive maintenance program with digital checklist',
  NULL,
  'maintenance',
  'Breakdowns pulled from the line unpredictably; reactive maintenance is 60-80% of wrench time; no PM compliance tracking.',
  '{"maintenance_approach":["reactive","ad_hoc"],"trucks_min":20}'::jsonb,
  5000,
  20000,
  'CMMS lite (Fiix, UpKeep, Limble) $20-50/user/month + config + training.',
  'truck_downtime_hours_per_month',
  -20,
  -45,
  'Available-fleet % +3 to +7 pp; breakdown-on-route rate cut in half.',
  8,
  'medium',
  ARRAY['workshop_supervisor_buy_in']::text[],
  false,
  'Workshop often dominated by one or two expat master mechanics; winning them over is critical.',
  '["Fiix / UpKeep SME fleet case studies [recall]"]'::jsonb,
  ARRAY['maintenance', 'fleet']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'predictive_maintenance_analytics',
  'Predictive maintenance on drum + drivetrain via telematics data',
  NULL,
  'maintenance',
  'Hydraulic and drum-bearing failures catch the fleet at peak; no leading indicators acted upon.',
  '{"telematics_coverage_pct_min":80,"cmms_in_place":true}'::jsonb,
  10000,
  40000,
  'Add-on module on telematics vendor + analytics engineer time.',
  'unplanned_downtime_hours',
  -15,
  -35,
  'Parts inventory -10 to -20%; critical-failure rate halved on addressed components.',
  16,
  'high',
  ARRAY['telematics_gps_basic', 'preventive_maintenance_program']::text[],
  false,
  'Heat + dust shorten component lifetime vs. OEM book values by 15-40%. Local empirical calibration beats manufacturer intervals.',
  '["Geotab MyGeotab marketplace case studies [recall]"]'::jsonb,
  ARRAY['maintenance', 'advanced']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'spare_parts_kanban',
  'Critical spares kanban + min-max rebuild',
  NULL,
  'maintenance',
  'Stockouts of high-frequency parts (filters, hoses, drum liners) drive unnecessary downtime; overstock of slow-movers ties up cash.',
  '{"parts_inventory_mgmt":["manual","spreadsheet","none"]}'::jsonb,
  2000,
  8000,
  '1-2 weeks analyst time + kanban cards + simple stock tool.',
  'parts_stockout_rate',
  -40,
  -70,
  'Working capital released 10-25% on parts lines; downtime due to parts-wait -30 to -60%.',
  3,
  'low',
  ARRAY[]::text[],
  true,
  'Import lead times for OEM (German/Italian) batching plant spares are 6-12 weeks; critical items need dual-source strategy.',
  '["Lean maintenance practice"]'::jsonb,
  ARRAY['maintenance', 'quick_win', 'inventory']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'driver_incentive_redesign',
  'Driver incentive structure redesign (trips + quality + safety)',
  NULL,
  'driver',
  'Pure per-trip incentive drives partial-load behaviour and unsafe speed; pure hourly drives slow-walking; current mix not aligned to TAT/reject goals.',
  '{"driver_pay_model_any_of":["per_trip_only","hourly_only","flat_monthly_only"]}'::jsonb,
  0,
  5000,
  'Process change; possibly HR legal review of labour contract amendments under Saudi Labour Law.',
  'partial_load_rate',
  -10,
  -30,
  'Safety incidents -10 to -30%; reject attribution fights shrink.',
  4,
  'medium',
  ARRAY['driver_pay_baseline_audit']::text[],
  false,
  'Driver workforce in KSA ready-mix is overwhelmingly South Asian; per-trip incentives are culturally entrenched. Any change needs Arabic + Urdu/Hindi communication and a ''nobody loses in month 1'' guarantee.',
  '["GCC labour market practice [recall]"]'::jsonb,
  ARRAY['driver', 'incentive', 'change_mgmt']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'driver_training_concrete_handling',
  'Driver training: concrete handling, slump discipline, defensive driving',
  NULL,
  'driver',
  'Uncontrolled water addition at site; aggressive driving in residential areas; poor customer-facing conduct.',
  '{"driver_training_hours_per_year_lt":8}'::jsonb,
  3000,
  12000,
  '1-2 days training per driver x 90 drivers x $30-80/driver-day. Plus trainer cost.',
  'reject_rate_pct',
  -20,
  -50,
  'Insurance claim rate -15 to -30%; fuel -2 to -5% from smoother driving.',
  4,
  'low',
  ARRAY[]::text[],
  true,
  'Delivered in Urdu or Hindi; Arabic materials for the subset of Saudi drivers.',
  '["Industry training vendors [recall]"]'::jsonb,
  ARRAY['driver', 'quality', 'quick_win']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'driver_app_etas_forms',
  'Driver smartphone app (ETAs, site forms, ticket signature)',
  NULL,
  'driver',
  'Paper tickets lost, late customer signatures, no ETA to site contact, WhatsApp chaos.',
  '{"dispatch_tool_current":["whatsapp","paper","excel"]}'::jsonb,
  4000,
  15000,
  'Module of tier-1 dispatch vendor; or standalone $8-20/driver/month.',
  'ticket_reconciliation_days',
  -60,
  -90,
  'DSO -5 to -15 days on invoicing; dispute rate -20 to -50%.',
  4,
  'low',
  ARRAY['driver_smartphone_penetration_gt_70pc_or_provided']::text[],
  false,
  'Provide company phones for non-smartphone drivers; SAR 80-150/mo line cost (~$22-40).',
  '["Sysdyne, TrackIt driver app case studies [recall]"]'::jsonb,
  ARRAY['driver', 'digital']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'slump_automation_qc',
  'Automated slump measurement at loading (ICAR / camera-based)',
  NULL,
  'qc',
  'Manual slump test is sampled (e.g. 1 in 10), subjective, and adds 2-4 min if done at gate.',
  '{"slump_test_process":["manual_sample"]}'::jsonb,
  15000,
  60000,
  'ICAR probe or camera-based ML slump. Per plant.',
  'slump_test_coverage_pct',
  300,
  900,
  'Reject rate -0.3 to -0.8 pp; sample cycle time near zero.',
  6,
  'medium',
  ARRAY['batch_controller_integration']::text[],
  false,
  'Dust + high temp challenge for vision systems; specify IP66 and active cooling.',
  '["ICAR rheometer papers [recall]","Sensocrete marketing [recall]"]'::jsonb,
  ARRAY['qc', 'automation']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'concrete_temperature_hot_weather',
  'Hot-weather concreting protocol (ice + chilled water + recipe temp cap)',
  NULL,
  'qc',
  'Summer pours exceed the 32 C paste temperature threshold, driving slump loss, set-time issues, and rejects on arrival.',
  '{"climate_zone":["hot_desert"],"reject_rate_pct_gt":1}'::jsonb,
  15000,
  80000,
  'Per plant: ice plant (block or flake), chiller on water line, insulated aggregate stockpile covers.',
  'reject_rate_summer_pct',
  -40,
  -75,
  'Customer complaints on set-time near eliminated in June-Sept.',
  10,
  'medium',
  ARRAY[]::text[],
  false,
  'ACI 305 ''Hot Weather Concreting'' is the reference standard. Saudi Building Code references ACI. Many GCC plants already have ice plants; the gap is usually protocol discipline.',
  '["ACI 305R-20 [recall]","Saudi Readymix IPO 2010 [recall]"]'::jsonb,
  ARRAY['qc', 'gcc_critical', 'seasonal']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'admixture_optimisation',
  'Admixture portfolio review + dosing optimisation',
  NULL,
  'qc',
  'Over-dosing superplasticiser; multiple suppliers with overlapping products; summer/winter dosing uncontrolled.',
  '{"admixture_spend_pct_of_cogs_gt":5}'::jsonb,
  2000,
  10000,
  'Free if supplier does it; else consultant + lab time.',
  'admixture_spend_pct',
  -8,
  -20,
  'Strength uniformity improves (std dev -10 to -25%).',
  4,
  'low',
  ARRAY[]::text[],
  true,
  'Riyadh admixture market dominated by Fosroc, Sika, BASF/MBCC, Chryso, CICO. Competitive tender annually is typical leverage.',
  '["ACI 212.3R on admixtures [recall]","Supplier customer cases [recall]"]'::jsonb,
  ARRAY['qc', 'quick_win', 'cost']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'reject_root_cause_system',
  'Reject root-cause capture + weekly review',
  NULL,
  'qc',
  'Rejects under-recorded (suspicious 1.5% reported = likely higher); causes assigned loosely; no closed-loop action.',
  '{"reject_recording_process":["manual","under_recorded_suspected","none"]}'::jsonb,
  500,
  3000,
  'Template + weekly 45-min review. If digital, piggy-back on dispatch tool.',
  'true_reject_rate_measured_pct',
  50,
  200,
  'Once true rate measured, targeted interventions reduce it; expect -20 to -40% over 6 months.',
  1,
  'low',
  ARRAY[]::text[],
  true,
  'Cultural resistance to recording rejects accurately (face, blame on driver). Framing must be ''diagnostic data'', not accountability weapon, for month 1.',
  '["Lean QC practice"]'::jsonb,
  ARRAY['qc', 'quick_win', 'diagnostic']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'partial_load_elimination_protocol',
  'Partial-load elimination protocol (min load rule + consolidation)',
  NULL,
  'dispatch',
  'Avg load well below drum capacity implies significant capacity loss. Root causes vary; protocol forces diagnosis + action.',
  '{"avg_load_m3_lt":8,"mixer_drum_capacity_m3_gte":8}'::jsonb,
  1000,
  5000,
  'Process + facilitation + dashboards. Impact comes from behaviour change, not tools.',
  'avg_load_m3',
  8,
  20,
  'Trips needed per 1000 m3 -8 to -17%; fleet can absorb volume growth without adding trucks.',
  4,
  'medium',
  ARRAY['order_intake_standardisation']::text[],
  true,
  'Partial loads often justified as ''keeping customer happy with a quick topper truck''. Needs owner endorsement to push back.',
  '["Internal derivation"]'::jsonb,
  ARRAY['dispatch', 'quick_win', 'high_leverage']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'night_shift_expansion',
  'Night-shift expansion enabled by megaproject night-pour demand',
  NULL,
  'batching',
  'Operating hours undershoot potential; Riyadh truck restrictions + customer megaproject night pours favour extended hours.',
  '{"operating_hours_per_day_lt":18,"megaproject_customer_share_gt":0.15}'::jsonb,
  20000,
  90000,
  'Primarily labour (shift allowance), lighting, security. Saudi Labour Law night premium typically 50% of base for 22:00-06:00.',
  'monthly_m3_capacity',
  20,
  50,
  'Mixer utilisation improves; Riyadh daytime truck restrictions dodged for some routes.',
  8,
  'medium',
  ARRAY['demand_pipeline_supports', 'maintenance_window_relocated']::text[],
  false,
  'Directly incentivised by RCRC truck-movement restrictions: night windows are when mixers can legally traverse restricted zones. Megaprojects pour at night to avoid heat.',
  '["Saudi Vision 2030 giga-project delivery schedules [recall]"]'::jsonb,
  ARRAY['batching', 'capacity', 'gcc_critical']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'subcontractor_haulier_integration',
  'Formal hire-fleet SLA + integrated telematics',
  NULL,
  'fleet',
  'Peak demand handled by ad-hoc hire trucks with no TAT visibility, no QC compliance, no data feeding the dispatch view.',
  '{"hire_fleet_share_of_trips_gt":0.05}'::jsonb,
  3000,
  15000,
  'Contract + telematics minimum spec + QC training for hire drivers.',
  'hire_fleet_tat_gap_min',
  -30,
  -60,
  'Reject attribution cleaner; own-fleet benchmark visible.',
  5,
  'medium',
  ARRAY[]::text[],
  false,
  'Saudization Nitaqat may push some hire-fleet arrangements off-books; formalise to avoid labour-ministry risk.',
  '["Industry practice"]'::jsonb,
  ARRAY['fleet', 'procurement']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;

INSERT INTO public.intervention_library (
  slug, title_en, title_ar, category, problem_solves, applicability_rules,
  cost_usd_low, cost_usd_high, cost_notes, impact_metric, impact_pct_low,
  impact_pct_high, impact_secondary, effort_weeks, complexity, prerequisites,
  quick_win, gcc_notes, sources, tags
) VALUES (
  'data_kpi_dashboard_exec',
  'Executive KPI dashboard (daily TAT / utilisation / reject / m3)',
  NULL,
  'dispatch',
  'Owner lacks daily line-of-sight; decisions made on gut or monthly lag reports; no early-warning of drift.',
  '{"exec_dashboard_exists":false}'::jsonb,
  1500,
  8000,
  'Google Data Studio / Power BI / Metabase on top of dispatch + batch data. Week of analyst time.',
  'management_response_lag_days',
  -70,
  -95,
  'All other interventions ROI becomes measurable, compounding value.',
  2,
  'low',
  ARRAY['data_sources_accessible']::text[],
  true,
  'Patriarch-owner should see it on WhatsApp daily at 7am; design for the phone first.',
  '["General BI practice"]'::jsonb,
  ARRAY['dispatch', 'quick_win', 'leadership']::text[]
) ON CONFLICT (slug) DO UPDATE SET
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  category = EXCLUDED.category,
  problem_solves = EXCLUDED.problem_solves,
  applicability_rules = EXCLUDED.applicability_rules,
  cost_usd_low = EXCLUDED.cost_usd_low,
  cost_usd_high = EXCLUDED.cost_usd_high,
  cost_notes = EXCLUDED.cost_notes,
  impact_metric = EXCLUDED.impact_metric,
  impact_pct_low = EXCLUDED.impact_pct_low,
  impact_pct_high = EXCLUDED.impact_pct_high,
  impact_secondary = EXCLUDED.impact_secondary,
  effort_weeks = EXCLUDED.effort_weeks,
  complexity = EXCLUDED.complexity,
  prerequisites = EXCLUDED.prerequisites,
  quick_win = EXCLUDED.quick_win,
  gcc_notes = EXCLUDED.gcc_notes,
  sources = EXCLUDED.sources,
  tags = EXCLUDED.tags;
