'use client'

import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import AssessmentShell from '@/components/assessment/AssessmentShell'
import type { Answers } from '@/lib/calculations'

// ─────────────────────────────────────────────────────────────────────────────
// Demo dataset: Al-Noor RMX, Dubai — consistent, realistic GCC scenario
//
// Plant profile:
//   10-truck fleet (8 operative), 10 h/day, 290 days/year, 22 days this month
//   Delivery radius 12 km → TARGET_TA = 78 min; actual turnaround 95 min (+17 min over target)
//   38 deliveries/day, 7 m³ trucks → ~5,900 m³/month
//   Rated capacity 30 m³/hr → utilisation ~89%, just below 92% target
//   Contribution margin: $68 − $26 − $7 − $3 = $32/m³
//   Reject rate 3.8%, plant absorbs full write-off
//   Dispatch via WhatsApp/spreadsheet, ~32 min order-to-dispatch
// ─────────────────────────────────────────────────────────────────────────────

const DEMO_ANSWERS: Answers = {

  // ── 1. Prices & costs ──────────────────────────────────────────────────────
  price_m3:           '68',
  cement_cost:        '26',
  aggregate_cost:     '7',
  admix_cost:         '3',
  fuel_per_delivery:  '11',       // USD per round trip
  water_cost:         '0',

  // Supply context
  silo_days:          '5 to 10 days — adequate',
  aggregate_days:     '2 to 5 days — tight, supply-sensitive',
  op_days:            '290',      // annual working days
  mix_split:          'Mostly standard strength — over 70% is C20 to C30',
  ramadan_schedule:   'Partially — informal earlier start, no formal plan',
  working_days_month: '22',
  typical_month:      'Yes — normal month, representative of typical operations',

  // ── 2. Trucks & delivery ───────────────────────────────────────────────────
  n_trucks:           '10',
  mixer_capacity:     '7',
  truck_availability: '8',        // 2 off-road (availability 80%)
  qualified_drivers:  '8',
  turnaround:         '95',       // min — 17 min above 78-min target
  deliveries_day:     '38',
  delivery_radius:    '12',       // km → TARGET_TA = 78 min
  partial_load_size:  '6.5',      // m³ per trip (93% of 7 m³ capacity → not a loss flag)
  site_wait_time:     '55',       // min at site — above 40-min best practice
  washout_time:       '10 to 20 minutes — standard',

  // ── 3. Production capacity ─────────────────────────────────────────────────
  plant_cap:          '30',       // m³/hr rated capacity
  op_hours:           '10',
  actual_prod:        '5900',     // m³ last month (38 del × 7 m³ × 22 days)
  batch_cycle:        'Normal — 5 to 7 minutes',
  batch_calibration:  '1 to 2 years ago',
  stops_freq:         '1 to 2 stops',
  operator_backup:    'Partially — someone could manage but has limited experience',
  mix_design_review:  '1 to 3 years ago',
  admix_strategy:     'Workability only — admixtures used to improve flow and placement',

  // ── 4. Dispatch coordination ───────────────────────────────────────────────
  dispatch_tool:      'Spreadsheet combined with WhatsApp',
  order_notice:       '4 to 24 hours — day-of or day-before',
  order_to_dispatch:  '25 to 40 minutes — slow',
  route_clustering:   'Sometimes — depends on the dispatcher',
  plant_idle:         'Occasionally — a few times per week',

  // ── 5. Quality & maintenance ───────────────────────────────────────────────
  maint_programme:    'Informal — some checks but no written programme',
  truck_breakdowns:   '3',        // unplanned breakdowns last month
  return_liability:   'Plant always absorbs the cost',
  demurrage_policy:   'Clause exists but rarely enforced',
  top_customer_pct:   '38',
  quality_control:    'Usually done — most trucks, informal recording',
  reject_pct:         '3.8',
  reject_cause:       'Heat and stiffening during transit',
  surplus_concrete:   '0.2 to 0.5 m³ — moderate',
  summer_cooling:     'Partial — cold tap water or shaded aggregate storage only',
  breakdowns:         '2 to 3 — acceptable',

  // ── 6. Data quality ────────────────────────────────────────────────────────
  prod_data_source:   'System records — read from batch computer or dispatch system',
  data_freshness:     "Today's operation — figures from this visit",
  data_observed:      'Seen on screen — batch computer, dispatch system, or printout',
  summer_prod_drop:   '10 to 20% — moderate drop',
}

// ─────────────────────────────────────────────────────────────────────────────
// Pre-written demo report — written as if generated by AI from the above data.
// All numbers are consistent with calc engine output for these answers.
// ─────────────────────────────────────────────────────────────────────────────

const DEMO_REPORT = {
  executive:
`Al-Noor RMX is operating with an overall performance score of 72/100. The plant's 10-truck fleet is producing roughly 5,900 m³ per month at 89% utilisation — 3 points below the 92% target. Fleet turnaround time is the primary financial constraint at 95 minutes against a 78-minute regional benchmark, costing an estimated $47,000–$54,000 per month in lost delivery capacity. Dispatch coordination and quality losses add a further $25,000–$30,000 per month. Total recoverable margin is in the range of $70,000–$80,000 per month — representing a 40–45% uplift on current contribution from operational improvements alone, without capital investment.`,

  diagnosis:
`Logistics (primary financial driver): The 95-minute turnaround is 17 minutes above the 78-minute benchmark for a 12 km delivery radius. Site wait time of 55 minutes is the single largest component — above the 40-minute industry benchmark — and the plant has no enforced demurrage clause to recover the cost from contractors. Each extra minute of turnaround costs approximately $3,200/month. Bringing turnaround to 82 minutes — a realistic 90-day target — would recover an estimated $41,000/month.

Dispatch (lowest score at 52/100): Order-to-dispatch averaging 32 minutes against a 15-minute target represents the most visible operational gap. Deliveries are routed ad hoc rather than by zone, and the plant manages dispatch via WhatsApp and spreadsheet with no real-time tracking. Truck idle time between dispatch and loading is compounding the turnaround problem.

Quality: A 3.8% rejection rate at $68/m³ with the plant absorbing 100% of write-off costs amounts to approximately $17,000/month. The dominant cause is heat-related stiffening during transit — expected in GCC summer conditions — but the plant has only partial cooling measures. Mix calibration has not been reviewed in 1–2 years, adding calibration drift risk.

Production: Utilisation at 89% is close to target but constrained downstream by the turnaround bottleneck. Three truck breakdowns last month on an informally maintained fleet, combined with 20% fleet unavailability (2 trucks regularly off-road), suggest maintenance is reactive rather than preventive.`,

  actions:
`1. Demurrage enforcement (immediate): Formalize the waiting time clause already in contracts. Set 45-minute site limit with a $25/15-min charge. A single firm conversation with the top 3 contractors recovers this within 30 days.

2. Dispatch SOP — order-to-dispatch under 20 minutes (Week 1–2): Restructure the morning sequence. Batch pre-load 3 trucks before first orders are confirmed. Assign a dedicated dispatcher rather than using the plant manager. Target: under 20 minutes by Week 4.

3. Turnaround audit (Week 1–2): Time-stamp 3 full truck cycles. Identify where the 95 minutes goes — typically 8–12 minutes are recoverable at weighbridge queuing and washout handover. Target: under 85 minutes within 30 days.

4. Zone-based dispatch routing (Week 3–4): Cluster consecutive deliveries by area. Group morning deliveries into 2–3 zones. Reduces transit per cycle by an estimated 8–12 minutes.

5. Preventive maintenance schedule (Week 2): Create a 4-week rotating service schedule for all 10 trucks. Three breakdowns per month on an 8-operative fleet is 37.5% above the 2-per-month benchmark. Each breakdown costs approximately $380 in lost contribution.

6. Activate 90-day tracking: Baseline turnaround (95 min), rejection rate (3.8%), and dispatch time (32 min) are established. Weekly logging takes 5 minutes per week and creates the before/after case study.`,
}

export default function DemoView() {
  const router = useRouter()
  const supabase = createClient()

  async function handleSignOut() {
    await supabase.auth.signOut()
    router.push('/login')
    router.refresh()
  }

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', background: 'var(--gray-50)' }}>

      {/* Top bar */}
      <div style={{
        background: 'var(--green)', padding: '0 24px',
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        height: '44px', flexShrink: 0,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            width: '28px', height: '28px', borderRadius: '8px',
            background: 'rgba(255,255,255,0.15)', display: 'flex',
            alignItems: 'center', justifyContent: 'center',
          }}>
            <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: '#5DCAA5' }} />
          </div>
          <span style={{ color: '#fff', fontSize: '15px', fontWeight: '500' }}>Al-RMX</span>
          <span style={{
            fontSize: '11px', color: 'rgba(255,255,255,0.6)',
            background: 'rgba(255,255,255,0.12)', padding: '2px 8px',
            borderRadius: '4px', marginLeft: '4px',
          }}>
            DEMO
          </span>
          <span style={{ fontSize: '12px', color: 'rgba(255,255,255,0.5)', marginLeft: '8px' }}>
            Al-Noor RMX · Dubai · June 2025
          </span>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <button onClick={() => router.push('/dashboard')} style={{
            fontSize: '12px', color: 'rgba(255,255,255,0.7)',
            background: 'none', border: '1px solid rgba(255,255,255,0.2)',
            borderRadius: '6px', padding: '4px 10px', cursor: 'pointer', fontFamily: 'var(--font)',
          }}>
            Go to platform
          </button>
          <button onClick={handleSignOut} style={{
            fontSize: '12px', color: 'rgba(255,255,255,0.7)',
            background: 'none', border: '1px solid rgba(255,255,255,0.2)',
            borderRadius: '6px', padding: '4px 10px', cursor: 'pointer', fontFamily: 'var(--font)',
          }}>
            Sign out
          </button>
        </div>
      </div>

      {/* Demo notice banner */}
      <div style={{
        background: '#FEF3C7', borderBottom: '1px solid #FDE68A',
        padding: '8px 24px', fontSize: '12px', color: '#92400E',
        display: 'flex', alignItems: 'center', gap: '8px',
      }}>
        <span>👁</span>
        <span>
          <strong>Demo mode</strong> — pre-loaded with a representative GCC ready-mix plant (Al-Noor RMX, Dubai).
          All scores, financial figures and findings are calculated live from the data below. Changes are not saved.
        </span>
      </div>

      {/* Full assessment shell — identical to live product */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
        <AssessmentShell
          initialAnswers={DEMO_ANSWERS}
          phase="onsite"
          season="summer"
          country="UAE"
          plant="Al-Noor RMX"
          date="2025-06-15"
          assessmentId="demo"
          report={DEMO_REPORT}
          reportReleased={true}
          isAdmin={true}
          onSave={() => { /* no-op in demo */ }}
        />
      </div>
    </div>
  )
}
